destination: ./_site
baseurl:     /
auto:        false
lsi:         false
server_port: 8080
pygments:    true
markdown:    maruku
#permalink:   date
permalink:   pretty
paginate:    5
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex/
  png_url:   /images/latex/
exclude:
  - README.txt
  - Rakefile
